version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "dohoudaniel"
    assignees:
      - "dohoudaniel"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Group minor and patch updates
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Separate major updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Allow security updates for major versions
    allow:
      - dependency-type: "all"
        update-type: "security"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "dohoudaniel"
    assignees:
      - "dohoudaniel"
    commit-message:
      prefix: "ci"
      include: "scope"
